# Generated by Django 4.2.30 on 2026-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolledstudent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrolledstudent',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='EnrollmentCode',
        ),
    ]
