# Generated by Django 4.2.30 on 2026-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pre_approved', 'Pre-Approved (Excel)'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
