# Generated by Django 4.2.30 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pre_approved', 'Pre-Approved (Excel)'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrolledstudent',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='enrolledstudent',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
