# Generated by Django 4.2.30 on 2026-05-06 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(choices=[('lecturer', 'Lecturer'), ('senior_lecturer', 'Senior Lecturer'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor')], max_length=50)),
                ('department', models.CharField(default='Computer Science', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('recommended_max_projects', models.PositiveIntegerField(default=3)),
                ('current_projects_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('research_interests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('project_title', models.CharField(blank=True, max_length=300)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('idea_pitch', 'Idea Pitch Submitted'), ('proposal_pending', 'Proposal Pending'), ('proposal_approved', 'Proposal Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='idea_pitch', max_length=30)),
                ('semester', models.CharField(help_text="e.g., 'Fall 2024'", max_length=20)),
                ('fydp_phase', models.CharField(choices=[('fydp1', 'FYDP-I'), ('fydp2', 'FYDP-II')], default='fydp1', max_length=20)),
                ('sdg_goals', models.JSONField(blank=True, default=list)),
                ('acm_knowledge_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervised_groups', to='projects.faculty')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_groups', to='projects.faculty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FYDPProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('domain', models.CharField(max_length=100)),
                ('nature_of_project', models.JSONField(help_text='Checkboxes for project type')),
                ('problem_statement', models.TextField(max_length=500)),
                ('proposed_solution', models.TextField()),
                ('scope_included', models.TextField()),
                ('scope_excluded', models.TextField(blank=True)),
                ('methodology', models.TextField()),
                ('resources_involved', models.TextField()),
                ('final_deliverables', models.TextField()),
                ('learning_outcomes', models.TextField()),
                ('industrial_support', models.TextField(blank=True)),
                ('industry_partner_name', models.CharField(blank=True, max_length=200)),
                ('sdg_mapping', models.JSONField(blank=True, default=dict)),
                ('ccp_mapping', models.JSONField(blank=True, default=dict)),
                ('acm_mapping', models.JSONField(blank=True, default=list)),
                ('project_schedule', models.FileField(blank=True, upload_to='proposals/schedules/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('committee_remarks', models.TextField(blank=True)),
                ('project_serial_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='projects.projectgroup')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('A1', 'Minor title modification - No penalty'), ('A2', 'Major scope change - 5% penalty'), ('B', 'Supervisor change - 10% penalty'), ('C', 'Member switch groups - 10% penalty'), ('D', 'Insufficient members - No special consideration'), ('E', 'Special circumstances - Forward to HOD')], max_length=2)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField()),
                ('supervisor_consent', models.BooleanField(default=False)),
                ('supervisor_remarks', models.TextField(blank=True)),
                ('penalty_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('penalty_applied', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_remarks', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, upload_to='change_requests/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='projects.projectgroup')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('lead', 'Group Lead')], default='member', max_length=30)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('earned_credit_hours', models.PositiveIntegerField()),
                ('prerequisites_completed', models.BooleanField(default=True)),
                ('has_special_permission', models.BooleanField(default=False)),
                ('permission_level', models.CharField(blank=True, choices=[('hod', 'HOD Approved'), ('dean', 'Dean Approved')], max_length=10, null=True)),
                ('permission_document', models.FileField(blank=True, upload_to='approvals/permission_letters/')),
                ('contribution_percentage', models.PositiveIntegerField(default=33)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.projectgroup')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'student__email'],
                'unique_together': {('group', 'student')},
            },
        ),
    ]
