# Generated by Django 4.2.30 on 2026-05-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='full_name',
            field=models.CharField(blank=True, help_text="Student's full name as per records", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='odoo_id',
            field=models.CharField(blank=True, help_text='University/Odoo ID (e.g., IU02-0322-0288)', max_length=50, null=True),
        ),
    ]
