# Generated by Django 4.2.30 on 2026-05-08 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_groupmember_full_name_groupmember_odoo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Admin Approval'), ('idea_pitch', 'Idea Pitch Submitted'), ('proposal_pending', 'Proposal Pending'), ('proposal_approved', 'Proposal Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='idea_pitch', max_length=30),
        ),
    ]
