# Generated by Django 4.2.30 on 2026-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectgroup_approved_at_projectgroup_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='group_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Admin Approval'), ('idea_pitch', 'Idea Pitch Submitted'), ('proposal_pending', 'Proposal Pending'), ('proposal_approved', 'Proposal Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
    ]
