# Generated by Django 4.2.30 on 2026-05-15 22:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_projectgroup_group_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_number', models.IntegerField(help_text='Meeting number (1-16)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('date', models.DateField()),
                ('agenda', models.TextField(help_text='Discussion agenda')),
                ('previous_task_status', models.CharField(blank=True, choices=[('complete', '✅ Completed'), ('incomplete', '❌ Incomplete'), ('partial', '⚠️ Partial')], max_length=20, null=True)),
                ('previous_task_comment', models.TextField(blank=True)),
                ('new_task', models.TextField(help_text='Tasks assigned for next week')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_minutes', to='projects.projectgroup')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_meetings', to='projects.faculty')),
            ],
            options={
                'ordering': ['meeting_number'],
                'unique_together': {('group', 'meeting_number')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='projects.meetingminute')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'student')},
            },
        ),
    ]
