# Generated by Django 4.2.30 on 2026-06-06 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_meetingminute_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fydpproposal',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text="Admin's final decision remarks"),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='approved_by_supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor who approved this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to='projects.faculty'),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='finally_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who gave final approval', limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finally_approved_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='proposal_file',
            field=models.FileField(blank=True, help_text='Upload filled proposal form (PDF/DOCX only, Max 10MB)', null=True, upload_to='proposals/documents/'),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='supervisor_remarks',
            field=models.TextField(blank=True, help_text="Supervisor's feedback"),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fydpproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved_by_supervisor', 'Approved by Supervisor'), ('revision_needed', 'Revision Needed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
