# Generated by Django 4.2.30 on 2026-06-27 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text="e.g., 'Fall 2024'", max_length=20)),
                ('fydp_phase', models.CharField(choices=[('fydp1', 'FYDP-I'), ('fydp2', 'FYDP-II')], default='fydp2', max_length=20)),
                ('deadline_date', models.DateTimeField(help_text='Report submission deadline')),
                ('late_submission_allowed', models.BooleanField(default=True, help_text='Allow late submissions with penalty/tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Deadline',
                'verbose_name_plural': 'Report Deadlines',
                'ordering': ['-deadline_date'],
                'unique_together': {('semester', 'fydp_phase')},
            },
        ),
        migrations.CreateModel(
            name='ProjectReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, help_text='Upload final project report (PDF/DOCX only, Max 20MB)', null=True, upload_to='project_reports/')),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved_by_supervisor', 'Approved by Supervisor'), ('revision_needed', 'Revision Needed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_reason', models.TextField(blank=True, help_text='Reason for late submission (if any)')),
                ('supervisor_remarks', models.TextField(blank=True, help_text="Supervisor's feedback")),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, help_text="Admin's final decision remarks")),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_similarity_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Internal plagiarism check score (0-100%)', max_digits=5)),
                ('internal_similarity_report', models.JSONField(blank=True, default=dict, help_text='Detailed similarity report with matched groups')),
                ('turnitin_similarity_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Manual Turnitin similarity score (admin enters)', max_digits=5, null=True)),
                ('plagiarism_check_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_supervisor', models.ForeignKey(blank=True, help_text='Supervisor who approved this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to='projects.faculty')),
                ('finally_approved_by', models.ForeignKey(blank=True, help_text='Admin who gave final approval', limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finally_approved_reports', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_submission', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Project Report Submission',
                'verbose_name_plural': 'Project Report Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
