# Generated by Django 4.2.30 on 2026-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_reportdeadline_projectreportsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminute',
            name='previous_task_status',
            field=models.CharField(blank=True, choices=[('complete', ' Completed'), ('incomplete', ' Incomplete'), ('partial', ' Partial')], max_length=20, null=True),
        ),
    ]
