# Generated by Django 4.2.30 on 2026-08-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_meetingminute_previous_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='earned_credit_hours',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='prerequisites_completed',
        ),
    ]
