# Generated by Django 4.2.30 on 2026-08-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_groupmember_cgpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='has_special_permission',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='permission_document',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='permission_level',
        ),
    ]
