# Generated by Django 4.2.30 on 2026-08-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_fydpproposal_max_submission_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreportsubmission',
            name='max_submission_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
