# Generated by Django 4.2.30 on 2026-08-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectreportsubmission_max_submission_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreportsubmission',
            name='internal_similarity_report',
        ),
        migrations.RemoveField(
            model_name='projectreportsubmission',
            name='internal_similarity_score',
        ),
        migrations.RemoveField(
            model_name='projectreportsubmission',
            name='plagiarism_check_completed',
        ),
    ]
