# Generated by Django 4.2.30 on 2026-08-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_projectreportsubmission_internal_similarity_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdeadline',
            options={'ordering': ['-deadline_date'], 'verbose_name': 'Submission Deadline', 'verbose_name_plural': 'Submission Deadlines'},
        ),
        migrations.AlterUniqueTogether(
            name='reportdeadline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fydpproposal',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportdeadline',
            name='deadline_type',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('report', 'Report')], default='report', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reportdeadline',
            unique_together={('semester', 'fydp_phase', 'deadline_type')},
        ),
    ]
