# Generated by Django 4.2.30 on 2026-07-02 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_reportdeadline_projectreportsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=200)),
                ('criteria_marks', models.JSONField(default=dict, help_text="e.g., {'criteria_id': score, ...}")),
                ('raw_total', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('final_marks', models.DecimalField(decimal_places=2, help_text='Scaled marks: (raw_total / 35) * 30', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('comments', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_report_evaluations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_evaluations', to='projects.projectgroup')),
                ('report_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.projectreportsubmission')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evaluator_name', models.CharField(max_length=200)),
                ('evaluator_type', models.CharField(choices=[('committee', 'Committee Member'), ('faculty', 'Faculty Member'), ('external', 'External Examiner')], default='committee', max_length=20)),
                ('presentation_criteria_marks', models.JSONField(default=dict, help_text='Criteria marks for presentation (out of 50)')),
                ('presentation_raw_total', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('viva_marks', models.JSONField(default=dict, help_text="e.g., {'student_id': marks, ...} (out of 5 each)")),
                ('total_raw', models.DecimalField(decimal_places=2, help_text='Presentation + Viva total (out of 55)', max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_presentation_evaluations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_evaluations', to='projects.projectgroup')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingLogEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(help_text='Name of committee member', max_length=200)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comments', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_meeting_evaluations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_log_evaluations', to='projects.projectgroup')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('sessional', 'Sessional/Progress'), ('report', 'Project Report'), ('presentation', 'Presentation')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('clo', models.CharField(blank=True, help_text='e.g., CLO2', max_length=50)),
                ('ga', models.CharField(blank=True, help_text='e.g., GA3: Problem Analysis', max_length=100)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Multiplier for marks')),
                ('max_marks', models.PositiveIntegerField(help_text='Maximum marks for this criterion (before weight)')),
                ('description_1', models.TextField(blank=True, help_text='Description for score 1')),
                ('description_2', models.TextField(blank=True)),
                ('description_3', models.TextField(blank=True)),
                ('description_4', models.TextField(blank=True)),
                ('description_5', models.TextField(blank=True, help_text='Description for score 5')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['evaluation_type', 'order', 'id'],
                'unique_together': {('evaluation_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SessionalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_marks', models.JSONField(default=dict, help_text="e.g., {'criteria_id': score, ...}")),
                ('raw_total', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('final_marks', models.DecimalField(decimal_places=2, help_text='Scaled marks: (raw_total / 50) * 20', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('comments', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessional_evaluations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessional_evaluations', to='projects.projectgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessional_evaluations', to='projects.groupmember')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FinalEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessional_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meeting_log_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('report_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('presentation_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_passed', models.BooleanField(default=False)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='projects.projectgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='projects.groupmember')),
            ],
            options={
                'ordering': ['-total_marks'],
                'unique_together': {('group', 'student')},
            },
        ),
    ]
