# Generated by Django 4.2.30 on 2026-07-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_reportdeadline_projectreportsubmission'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetinglogevaluation',
            unique_together={('group',)},
        ),
    ]
