# Generated by Django 4.2.30 on 2026-07-07 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_meetinglogevaluation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationevaluation',
            name='presentation_criteria_marks',
            field=models.JSONField(blank=True, default=dict, help_text='Criteria marks for presentation (out of 50)'),
        ),
        migrations.AlterField(
            model_name='presentationevaluation',
            name='presentation_raw_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='presentationevaluation',
            name='total_raw',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Presentation + Viva total (out of 55)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='presentationevaluation',
            name='viva_marks',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'student_id': marks, ...} (out of 5 each)"),
        ),
    ]
