# Generated by Django 4.2.30 on 2026-08-17 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_reportdeadline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0003_alter_presentationevaluation_presentation_criteria_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleDefenseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('project_committee', 'Project Committee'), ('evaluation_committee', 'Evaluation Committee')], max_length=25)),
                ('evaluator_name', models.CharField(blank=True, max_length=200)),
                ('criteria_marks', models.JSONField(blank=True, default=dict)),
                ('raw_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('converted_marks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_title_defense_evaluations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_defense_evaluations', to='projects.projectgroup')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'unique_together': {('group', 'role')},
            },
        ),
    ]
